// cart.js
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_TO_SELECTED = 'ADD_TO_SELECTED'
export const REMOVE_FROM_SELECTED = 'REMOVE_FROM_SELECTED'
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'

// products.js
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_BY_PROPDUCT_ID = 'GET_BY_PROPDUCT_ID'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
